
---
title: "variables and stratification"
author: "Lucy Grigoroff"
date: "2023-11-01"
output: html_document
---

```{r}
#load("~/Documents/COMET/Data/data2769.RData")
load("~/Downloads/redo2769.Rdata")
load("~/Downloads/OneDrive_1_09-11-2023/500samplesforfigures.RData")
#load("~/git/75000089/COMET/SerumCometCompleteOnly.Rdata")

functionDir <- "/Users/lucygrigoroff/git/phenological/mva-plots/R/"
functionList <- list.files(path = functionDir)
for(i in functionList){
  source(paste0(functionDir,i))
}

# save(MAR,
#      MNAR,
#      MCAR,
#      SCdf,
#      file = "redo2769.Rdata")

```

#PCAs

Show which has the most separation in the metadata, this is company. Is it better to have Company as a variable in imputation or to stratify by company. 
```{r}
a <- PCA(data= SCdf[12:22])

b <- plotScores(model = a, optns = list(plotTitle = "Original",ellipse = "hotellings", color = SCdf$Company,  outlierLabels = row.names(SCdf)))

idx<-which(rownames(SCdf) %in% b[["data"]][["outliers"]][["PC1vPC2"]][["outlierID"]])

SCdf2<-SCdf[-idx,]

c <- PCA(data= SCdf2[12:22])

Toxin<- plotScores(model = c, optns = list(plotTitle = "Toxin", 
                                                  ellipse = "color", 
                                                  color = SCdf2$Toxin, 
                                               discretePalette =c("#bef7ff", "#c0f1ff", "#c2ebff", "#c4e5ff", "#c6dfff", "#c8d9ff", "#cad3ff", "#cccdff", "#cec8ff", "#d0c2ff", "#d2bcff", "#d4b6ff", "#d6b0ff", "#d8aaff", "#daa4ff", "#dd9eff", "#df98ff", "#e192ff", "#e38cff", "#e586ff", "#e780ff", "#e97aff", "#eb75ff", "#ed6fff", "#ef69ff", "#f163ff", "#f35dff", "#f557ff", "#f751ff", "#f94bff", "#ffe434", "#fbdd34", "#f8d734", "#f4d035", "#f0c935", "#ecc235", "#e9bc35", "#e5b536", "#e1ae36", "#dda736", "#daa136", "#d69a37", "#d29337", "#cf8d37", "#cb8637", "#c77f38", "#c37838", "#c07238", "#bc6b38", "#b86439", "#b55e39", "#b15739", "#ad5039", "#a9493a", "#a6433a", "#a23c3a", "#9e353a", "#9a2e3b", "#97283b", "#93213b", "#20ff20", "#26c53d", "#2c8a5a", "#315076", "#371593"),
                                                  PCi = 1,
                                                  PCj = 2,
                                                  size = 1,
                                                theme = theme(legend.position = "none")
                                                ))


Study_id<- plotScores(model = c, optns = list(plotTitle = "Study_id", 
                                                  ellipse = "color", 
                                                  color = SCdf2$Study_id, 
                                               discretePalette =c("#bef7ff", "#c0f1ff", "#c2ebff", "#c4e5ff", "#c6dfff", "#c8d9ff", "#cad3ff", "#cccdff", "#cec8ff", "#d0c2ff", "#d2bcff", "#d4b6ff", "#d6b0ff", "#d8aaff", "#daa4ff", "#dd9eff", "#df98ff", "#e192ff", "#e38cff", "#e586ff", "#e780ff", "#e97aff", "#eb75ff", "#ed6fff", "#ef69ff", "#f163ff", "#f35dff", "#f557ff", "#f751ff", "#f94bff", "#ffe434", "#fbdd34", "#f8d734", "#f4d035", "#f0c935", "#ecc235", "#e9bc35", "#e5b536", "#e1ae36", "#dda736", "#daa136", "#d69a37", "#d29337", "#cf8d37", "#cb8637", "#c77f38", "#c37838", "#c07238", "#bc6b38", "#b86439", "#b55e39", "#b15739", "#ad5039", "#a9493a", "#a6433a", "#a23c3a", "#9e353a", "#9a2e3b", "#97283b", "#93213b", "#20ff20", "#26c53d", "#2c8a5a", "#315076", "#371593", "red"),
                                                  PCi = 1,
                                                  PCj = 2,
                                                  size = 1,
                                                theme = theme(legend.position = "none")
                                                ))

Company <- plotScores(model = c, optns = list(plotTitle = "Company", 
                                                  ellipse = "color", 
                                                  color = SCdf2$Company, 
                                                  PCi = 1,
                                                  PCj = 2,
                                                  size = 1
                                                ))

DoseFlag <- plotScores(model = c, optns = list(plotTitle = "DoseFlag", 
                                                  ellipse = "color", 
                                                  color = SCdf2$doseFlag, 
                                                  PCi = 1,
                                                  PCj = 2,
                                                  size = 1
                                                ))

Target <- plotScores(model = c, optns = list(plotTitle = "Target", 
                                                  ellipse = "color", 
                                                  color = SCdf2$Target, 
                                                  PCi = 1,
                                                  PCj = 2,
                                                  size = 1
                                                ))

Timepoint <- plotScores(model = c, optns = list(plotTitle = "Timepoint", 
                                                  ellipse = "color", 
                                                  color = SCdf2$Timepoint, 
                                                  PCi = 1,
                                                  PCj = 2,
                                                  size = 1
                                                ))


ggarrange(plotlist = list(Company, Timepoint, Target, Toxin, DoseFlag, Study_id), ncol = 2)

```
#setup
```{r}
t <- MNAR

library(mice)
library(missForest)
library(tidyverse)
library(sjmisc)

impcols <- c(
  "Company"
  ,
  "Timepoint",
  "Animal_no.",
  "doseFlag",
  "Sacrifice_subgroup",
  "Target"
  ,
  "Toxin"
             )

SCdf<- full500

#column to begin creating missingness
start <- which(colnames(SCdf) == "S_Creatinine")
#or start<-12
end<-ncol(SCdf)

#missing percentages
p <- (cbind(0.05, 0.1, 0.2, 0.3, 0.4))

#for graphs in METRICS and FIGURES
cat(paste(shQuote(paste0( p[1,] * 100, " %"), type="cmd"), collapse=", "))
rn<-c("5 %", "10 %", "20 %", "30 %", "40 %")

#for refence
#full<- SCdf
full<-SCdf[,start:end]
#```

#set up original Albumin and Total Protein Bias
#```{r}
#set up external checks
original.lm.1 <- summary(lm(S_Albumin ~ S_Total_protein, data = SCdf))
# original.lm.1[["r.squared"]]
original <-original.lm.1[["coefficients"]][2,1]

missed<-list()
missedSummary<-list()
missedBias<-list()
for(j in 1:length(t)){
  missedSummary[[j]] <- summary(lm(S_Albumin ~ S_Total_protein, data = t[[j]], na.action = na.omit))
  missed[[j]] <-missedSummary[[j]][["coefficients"]][2,1]
  missedBias[[j]] <- abs((original - missed[[j]])/original)
}
#```
#set up original AST adn ALT
#```{r}
####################
original.lm.2 <- summary(lm(S_ALT ~ S_AST, data = SCdf))
# original.lm.1[["r.squared"]]
original2 <-original.lm.2[["coefficients"]][2,1]

missed2<-list()
missedSummary2<-list()
missedBias2<-list()
for(j in 1:length(t)){
  missedSummary2[[j]] <- summary(lm(S_ALT ~ S_AST, data = t[[j]], na.action = na.omit))
  missed2[[j]] <-missedSummary2[[j]][["coefficients"]][2,1]
  missedBias2[[j]] <- abs((original2 - missed2[[j]])/original2)
}
```



#unstratified

```{r, results='hide', message=FALSE, warning=FALSE}
#full<-SCdf[,12:22]
##MICErf
impcols_list<- list(NULL, "Company", c( "Company" ,
                                        "Timepoint",
                                        "Animal_no.",
                                       "doseFlag",
                                       "Sacrifice_subgroup",
                                       "Target" ))
for(impcols in impcols_list){
  
#####################################################MICErf
results_list <- list()
for(k in 1:20){
test<-list()
imp<-list()
imp2<-list()
imputedonly<-list()
MICErf<-list()
FULL<-list()
PARTIAL<-list()
for(j in 1:length(t)){
  placeHolder <- paste0("FULLimputed ", p[j] * 100, " %")
  placeHolder2 <- paste0("imputed vs full ", p[j] * 100, " %")
 
 if(length(impcols) == 1){
   x<-as.data.frame(SCdf[,impcols])
   colnames(x) <- c("Company")
 }
 
  if(length(impcols) > 1){
   x<-SCdf[,impcols]
  }
 
   if(length(impcols) < 1){
   x<-as.data.frame(rep_len(x=1, length.out = nrow(SCdf)))
 }
  
#make predictors numeric
  
 x[sapply(x, is.character)] <- lapply(x[sapply(x, is.character)], as.factor)
 x[sapply(x, is.factor)] <- lapply(x[sapply(x, is.factor)], as.numeric)
 
#make the predictor matrix using all covariates (including clin_chem parameters)
x<-cbind(x,t[[j]][,start:end])
init = mice(x, maxit=0) 
predM = init$predictorMatrix

#Do imputation
imp[[j]]<-mice(data = x, method="rf", predictorMatrix = predM)
imp2[[j]]<-merge_imputations(dat = x, imp = imp[[j]])
idx<- as.data.frame(which(is.na(t[[j]][,start:end]), arr.ind=TRUE))
idx$imputed<-idx$original<-NA

for(i in 1:nrow(idx)){
  idx$original[i]<-unlist(full[idx$row[i],idx$col[i]])
  idx$imputed[i]<-imp2[[j]][idx$row[i],idx$col[i]]
  imputedonly[[j]]<-idx
}

new_list <- setNames(list(imp2[[j]]), placeHolder)
FULL <- append(FULL, new_list)  

new_list2 <- setNames(list(imputedonly[[j]]), placeHolder2)
PARTIAL <- append(PARTIAL, new_list2) 
}

MICErf<- append(MICErf, list(PARTIAL = PARTIAL,
                             FULL = FULL))

#NRMSE + fullMAE
nrmse <-list()
fullmae<-list()
NRMSE<-list()
fullMAE<-list()
for(j in 1:length(MICErf[["FULL"]])){
  
placeHolder3 <- paste0( p[,j] * 100, " % missing")  

xi<- as.matrix(MICErf[["FULL"]][[j]])
xt<-as.matrix(SCdf[,start:end])
xm<-as.matrix(t[[j]][,start:end]) 
  
nrmse[[j]]<-missForest::nrmse(ximp = xi, xmis = xm, xtrue = xt)

new_list <- setNames((nrmse[j]), placeHolder3)
NRMSE <- append(NRMSE, new_list) 

fullmae[j] <- mean(abs(xt - xi))

new_list2 <- setNames((fullmae[j]), placeHolder3)
fullMAE <- append(fullMAE, new_list2) 

}
 
#partialMAE
 partialmae <- list()  
 partialMAE<-list()
  for(j in 1:length(MICErf[["PARTIAL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
    
  xt <- MICErf[["PARTIAL"]][[j]][["original"]]
  xi <- MICErf[["PARTIAL"]][[j]][["imputed"]]
  
  partialmae[j] <- mean(abs(xt - xi))
  
  new_list <- setNames((partialmae[j]), placeHolder3)
  partialMAE <- append(partialMAE, new_list) 
  }
 
#External check 1 MICErf
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.1 <- list()
for(j in 1:length(MICErf[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_Albumin ~ S_Total_protein, data = MICErf[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original - imputed[[j]])/original)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.1 <- append(imputedBias.1, new_list) 
}

#External Check 2 MICErf
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.2 <- list()
for(j in 1:length(MICErf[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_ALT ~ S_AST, data = MICErf[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original2 - imputed[[j]])/original2)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.2 <- append(imputedBias.2, new_list) 
}

MICErf<- append(MICErf, list(NRMSE = NRMSE,
                             partialMAE = partialMAE,
                             fullMAE = fullMAE,
                             imputedBias.1 = imputedBias.1,
                             imputedBias.2 = imputedBias.2))

results_list[[k]] <- MICErf

}

#nameing

 if((MCAR[1] %in% t[1])){
   missing<-"_MCAR"
 }

if((MAR[1] %in% t[1]) ){
  missing <-"_MAR"
}

if((MNAR[1] %in% t[1]) ){
  missing <-"_MNAR"
}

if(length(impcols) == 1){
   impco<- "_Company"
 }
 
  if(length(impcols) > 1){
  impco<- "_All"
  }
 
  # if(length(impcols) > 1){
  # impco<- "_All_Toxin"
  # }
   if(length(impcols) < 1){
   impco<-"_noMeta"
 }

list_name <- paste("MICErf", missing, impco, sep = "")
assign(list_name, results_list, envir = .GlobalEnv)

n_entries <- length(results_list)
metrics <- c("NRMSE", "partialMAE", "fullMAE", "imputedBias.1", "imputedBias.2")

# Initialize a list to store the results
results <- list()

# Loop through the metrics
for (metric in metrics) {
  result_matrix <- matrix(NA, nrow = n_entries, ncol = length(results_list[[1]][[metric]]))
  
  # Loop through the list and extract the current metric values into the matrix
  for (i in 1:n_entries) {
    result_matrix[i, ] <- unlist(results_list[[i]][[metric]])
  }
  
  # Calculate mean and standard deviation for each column
  mean_values <- apply(result_matrix, 2, mean)
  std_dev_values <- apply(result_matrix, 2, sd)
  
  results[[metric]] <- list(mean = mean_values, std_dev = std_dev_values)
}

list_name <- paste("summary_MICErf", missing, impco, sep = "")
assign(list_name, results, envir = .GlobalEnv)


#```

######################################################################################missForest
#```{r}

results_list <- list()
for(k in 1:20){
FULL<-list()
PARTIAL <- list()
missForest<-list()
imp <- list()
imputedonly<-list()
nrmse<-list()
NRMSE<-list()
for(j in 1:length(t)){
  placeHolder <- paste0("FULLimputed ", p[j] * 100, " %")
  placeHolder2 <- paste0("imputed vs full ", p[j] * 100, " %")
  placeHolder3<- paste0("NRMSE ", p[j] * 100, " % missing")
 
 if(length(impcols) == 1){
   x<-as.data.frame(SCdf[,impcols])
   colnames(x) <- c("Company")
 }
 
  if(length(impcols) > 1){
   x<-SCdf[,impcols]
  }
 
   if(length(impcols) < 1){
   x<-as.data.frame(rep_len(x=1, length.out = nrow(SCdf)))
 }
 
 #make predictors factors (can also be numeric, just not characters, max of 53 categories per variable allowed) 
 
 x[sapply(x, is.character)] <- lapply(x[sapply(x, is.character)], as.factor)
 
 #set up data frame used in imputation 
 x <- cbind(x,t[[1]][,start:end])

 ################## 
 #impute
 imp[[j]] <- missForest(xmis = x, ntree = 10, variablewise = F)
 ##################
 
 #locate where in the complete data the NAs were created
idx<- as.data.frame(which(is.na(t[[j]][,start:end]), arr.ind=TRUE))

#make empty list to fill with original and imputed
idx$imputed<-idx$original<-NA

#start and end criteria 
#start2 <- ncol(SCdf[,impcols]) +1
start2 <- which(colnames(x) == "S_Creatinine")
end2 <- ncol(x)

for(i in 1:nrow(idx)){
  
  #fill original column
  idx$original[i]<-full[idx$row[i],idx$col[i]]
  #fill imputed column
  idx$imputed[i]<-imp[[j]][["ximp"]][,start2:end2][idx$row[i],idx$col[i]]
  #store imputed only for each percentage of missingness
  imputedonly[[j]]<-idx
}

new_list <- setNames(list(imp[[j]][["ximp"]][,start2:end2]), placeHolder)
FULL <- append(FULL, new_list)  

 new_list2 <- setNames(list(imputedonly[[j]]), placeHolder2)
 PARTIAL <- append(PARTIAL, new_list2) 

}

missForest<- append(missForest, list(PARTIAL = PARTIAL,
                                     FULL = FULL
                                     ))

#NRMSE + fullMAE
nrmse <-list()
fullmae<-list()
NRMSE<-list()
fullMAE<-list()
for(j in 1:length(missForest[["FULL"]])){
  
placeHolder3 <- paste0( p[,j] * 100, " % missing")  

xi<- as.matrix(missForest[["FULL"]][[j]])
xt<-as.matrix(SCdf[,start:end])
xm<-as.matrix(t[[j]][,start:end]) 
  
nrmse[[j]]<-missForest::nrmse(ximp = xi, xmis = xm, xtrue = xt)

new_list <- setNames((nrmse[j]), placeHolder3)
NRMSE <- append(NRMSE, new_list) 

fullmae[j] <- mean(abs(xt - xi))

new_list2 <- setNames((fullmae[j]), placeHolder3)
fullMAE <- append(fullMAE, new_list2) 

}
 
#partialMAE
 partialmae <- list()  
 partialMAE<-list()
  for(j in 1:length(missForest[["PARTIAL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
    
  xt <- missForest[["PARTIAL"]][[j]][["original"]]
  xi <- missForest[["PARTIAL"]][[j]][["imputed"]]
  
  partialmae[j] <- mean(abs(xt - xi))
  
  new_list <- setNames((partialmae[j]), placeHolder3)
  partialMAE <- append(partialMAE, new_list) 
  }
 
#External check 1 missForest
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.1 <- list()
for(j in 1:length(missForest[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_Albumin ~ S_Total_protein, data = missForest[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original - imputed[[j]])/original)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.1 <- append(imputedBias.1, new_list) 
}

#External check 2 missForest
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.2 <- list()
for(j in 1:length(missForest[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_ALT ~ S_AST, data = missForest[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original2 - imputed[[j]])/original2)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.2 <- append(imputedBias.2, new_list) 
}
 
missForest<- append(missForest, list(NRMSE = NRMSE,
                                     partialMAE = partialMAE,
                                     fullMAE = fullMAE,
                                     imputedBias.1 = imputedBias.1,
                                     imputedBias.2 = imputedBias.2))  
results_list[[k]] <- missForest

}

#nameing

 if((MCAR[1] %in% t[1])){
   missing<-"_MCAR"
 }

if((MAR[1] %in% t[1]) ){
  missing <-"_MAR"
}

if((MNAR[1] %in% t[1]) ){
  missing <-"_MNAR"
}

if(length(impcols) == 1){
   impco<- "_Company"
 }
 
  if(length(impcols) > 1){
  impco<- "_All"
  }
 
   if(length(impcols) < 1){
   impco<-"_noMeta"
 }

list_name <- paste("missForest", missing, impco, sep = "")
assign(list_name, results_list, envir = .GlobalEnv)

n_entries <- length(results_list)
metrics <- c("NRMSE", "partialMAE", "fullMAE", "imputedBias.1", "imputedBias.2")

# Initialize a list to store the results
results <- list()

# Loop through the metrics
for (metric in metrics) {
  result_matrix <- matrix(NA, nrow = n_entries, ncol = length(results_list[[1]][[metric]]))
  
  # Loop through the list and extract the current metric values into the matrix
  for (i in 1:n_entries) {
    result_matrix[i, ] <- unlist(results_list[[i]][[metric]])
  }
  
  # Calculate mean and standard deviation for each column
  mean_values <- apply(result_matrix, 2, mean)
  std_dev_values <- apply(result_matrix, 2, sd)
  
  results[[metric]] <- list(mean = mean_values, std_dev = std_dev_values)
}

list_name <- paste("summary_missForest", missing, impco, sep = "")
assign(list_name, results, envir = .GlobalEnv)

}

```





#stratified 
Only use when Company is included in impcols

```{r, results='hide', message=FALSE, warning = FALSE}

impcols_list<- list("Company", c( "Company" ,
                                        "Timepoint",
                                        "Animal_no.",
                                       "doseFlag",
                                       "Sacrifice_subgroup",
                                       "Target" ))
for(impcols in impcols_list){

#library(sjmisc)
######################################################################MICErf strata
results_list <- list()
for(k in 1:20){
  #test<-list()
imp<-list()
imp2<-list()
imputedonly<-list()
MICErf<-list()
FULL<-list()
PARTIAL<-list()
for(j in 1:length(t)){
  placeHolder <- paste0("FULLimputed ", p[j] * 100, " %")
  placeHolder2 <- paste0("imputed vs full ", p[j] * 100, " %")
 
 if(length(impcols) == 1){
   x<-as.data.frame(SCdf[,impcols])
   colnames(x) <- c("Company")
 }
 
  if(length(impcols) > 1){
   x<-SCdf[,impcols]
  }
 
   if(length(impcols) < 1){
   x<-as.data.frame(rep_len(x = 1, length.out = nrow(SCdf)))
 }
  
#make predictors numeric
  
 x[sapply(x, is.character)] <- lapply(x[sapply(x, is.character)], as.factor)
 x[sapply(x, is.factor)] <- lapply(x[sapply(x, is.factor)], as.numeric)
 
#make the predictor matrix using all covariates (including clin_chem parameters)
x<-cbind(x,t[[j]][,start:end])
init = mice(x, maxit=0) 
predM = init$predictorMatrix

#Do imputation

rm(stratimp)
stratimp2<- list()
for(i in 1:5){
stratimp<-mice(data = x[which(x$Company == i),], method="rf", predictorMatrix = predM)
stratimp2[[i]]<-merge_imputations(dat = x[which(x$Company == i),], imp = stratimp)

#if the number of columns are less than 11, then one of them did not contain an NA post stratification, which will prevent the next step. If this is the case, find the column, reattach is and put it in the correct/same order as the others. May only work when it's one column missing
if(ncol(stratimp2[[i]]) < 11){
  #find missing column
base <- c("S_Creatinine", "S_Urea_nitrogen", "S_ALT", "S_AST", "S_Glucose", "S_Sodium", "S_Potassium", "S_Calcium", "S_Phosphorus", "S_Albumin", "S_Total_protein")
missing_cols <- setdiff(base, colnames(stratimp2[[i]]))

#reattach the column
stratimp2[[i]][,missing_cols] <- x[which(x$Company == i), missing_cols]

# Reorder columns in the data frame
stratimp2[[i]] <- stratimp2[[i]][, base]
}

}
test <- rbind(stratimp2[[1]], stratimp2[[2]], stratimp2[[3]], stratimp2[[4]], stratimp2[[5]])

imp2[[j]] <- test

idx<- as.data.frame(which(is.na(t[[j]][,start:end]), arr.ind=TRUE))
idx$imputed<-idx$original<-NA

for(i in 1:nrow(idx)){
  idx$original[i]<-unlist(full[idx$row[i],idx$col[i]])
  idx$imputed[i]<-imp2[[j]][idx$row[i],idx$col[i]]
  imputedonly[[j]]<-idx
}

new_list <- setNames(list(imp2[[j]]), placeHolder)
FULL <- append(FULL, new_list)  

new_list2 <- setNames(list(imputedonly[[j]]), placeHolder2)
PARTIAL <- append(PARTIAL, new_list2) 
}

MICErf<- append(MICErf, list(PARTIAL = PARTIAL,
                             FULL = FULL))

#NRMSE + fullMAE
nrmse <-list()
fullmae<-list()
NRMSE<-list()
fullMAE<-list()
for(j in 1:length(MICErf[["FULL"]])){
  
placeHolder3 <- paste0( p[,j] * 100, " % missing")  

xi<- as.matrix(MICErf[["FULL"]][[j]])
xt<-as.matrix(SCdf[,start:end])
xm<-as.matrix(t[[j]][,start:end]) 
  
nrmse[[j]]<-missForest::nrmse(ximp = xi, xmis = xm, xtrue = xt)

new_list <- setNames((nrmse[j]), placeHolder3)
NRMSE <- append(NRMSE, new_list) 

fullmae[j] <- mean(abs(xt - xi))

new_list2 <- setNames((fullmae[j]), placeHolder3)
fullMAE <- append(fullMAE, new_list2) 

}
 
#partialMAE
 partialmae <- list()  
 partialMAE<-list()
  for(j in 1:length(MICErf[["PARTIAL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
    
  xt <- MICErf[["PARTIAL"]][[j]][["original"]]
  xi <- MICErf[["PARTIAL"]][[j]][["imputed"]]
  
  partialmae[j] <- mean(abs(xt - xi))
  
  new_list <- setNames((partialmae[j]), placeHolder3)
  partialMAE <- append(partialMAE, new_list) 
  }
 
#External check 1 MICErf
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.1 <- list()
for(j in 1:length(MICErf[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_Albumin ~ S_Total_protein, data = MICErf[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original - imputed[[j]])/original)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.1 <- append(imputedBias.1, new_list) 
}

#External Check 2 MICErf
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.2 <- list()
for(j in 1:length(MICErf[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_ALT ~ S_AST, data = MICErf[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original2 - imputed[[j]])/original2)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.2 <- append(imputedBias.2, new_list) 
}

MICErf<- append(MICErf, list(NRMSE = NRMSE,
                             partialMAE = partialMAE,
                             fullMAE = fullMAE,
                             imputedBias.1 = imputedBias.1,
                             imputedBias.2 = imputedBias.2))

results_list[[k]] <- MICErf

}

#nameing

 if((MCAR[1] %in% t[1])){
   missing<-"_MCAR"
 }

if((MAR[1] %in% t[1]) ){
  missing <-"_MAR"
}

if((MNAR[1] %in% t[1]) ){
  missing <-"_MNAR"
}

if(length(impcols) == 1){
   impco<- "_Company"
 }
 
  if(length(impcols) > 1){
  impco<- "_All"
  }
 
   if(length(impcols) < 1){
   impco<-"_noMeta"
 }

list_name <- paste("MICErf_strata", missing, impco, sep = "")
assign(list_name, results_list, envir = .GlobalEnv)

n_entries <- length(results_list)
metrics <- c("NRMSE", "partialMAE", "fullMAE", "imputedBias.1", "imputedBias.2")

# Initialize a list to store the results
results <- list()

# Loop through the metrics
for (metric in metrics) {
  result_matrix <- matrix(NA, nrow = n_entries, ncol = length(results_list[[1]][[metric]]))
  
  # Loop through the list and extract the current metric values into the matrix
  for (i in 1:n_entries) {
    result_matrix[i, ] <- unlist(results_list[[i]][[metric]])
  }
  
  # Calculate mean and standard deviation for each column
  mean_values <- apply(result_matrix, 2, mean)
  std_dev_values <- apply(result_matrix, 2, sd)
  
  results[[metric]] <- list(mean = mean_values, std_dev = std_dev_values)
}

list_name <- paste("summary_MICErf_strata", missing, impco, sep = "")
assign(list_name, results, envir = .GlobalEnv)

# Now, `results` is a list containing mean and standard deviation for each metric.

#```




##########################################################################missForest strata
# Do 20 iterations
# ```{r}
results_list <- list()
for(k in 1:20){
FULL<-list()
PARTIAL <- list()
missForest<-list()
imp <- list()
imputedonly<-list()
nrmse<-list()
NRMSE<-list()
for(j in 1:length(t)){
  placeHolder <- paste0("FULLimputed ", p[j] * 100, " %")
  placeHolder2 <- paste0("imputed vs full ", p[j] * 100, " %")
  placeHolder3<- paste0("NRMSE ", p[j] * 100, " % missing")
 
 if(length(impcols) == 1){
   x<-as.data.frame(SCdf[,impcols])
   colnames(x) <- c("Company")
 }
 
  if(length(impcols) > 1){
   x<-SCdf[,impcols]
  }
 
   if(length(impcols) < 1){
   x<-as.data.frame(rep_len(x=1, length.out = nrow(SCdf)))
 }
 
 #make predictors factors (can also be numeric, just not characters, max of 53 categories per variable allowed) 
 
 x[sapply(x, is.character)] <- lapply(x[sapply(x, is.character)], as.factor)
 
 #set up data frame used in imputation 
 x <- cbind(x,t[[1]][,start:end])

 ################## 
#rm(stratimp)
stratimp2<- list()
companies <- c("D", "L", "N", "R", "S")

for (i in 1:5) {
  stratimp2[[i]] <- missForest(xmis = x[x$Company == companies[i], ], ntree = 10, variablewise = FALSE)
}
test <- rbind(stratimp2[[1]][["ximp"]], stratimp2[[2]][["ximp"]], stratimp2[[3]][["ximp"]], stratimp2[[4]][["ximp"]], stratimp2[[5]][["ximp"]])

imp[[j]] <- test
 
 ##################
 
 #locate where in the complete data the NAs were created
idx<- as.data.frame(which(is.na(t[[j]][,start:end]), arr.ind=TRUE))

#make empty list to fill with original and imputed
idx$imputed<-idx$original<-NA

#start and end criteria 
start2 <- which(colnames(x) == "S_Creatinine")
end2 <- ncol(x)

for(i in 1:nrow(idx)){
  
  #fill original column
  idx$original[i]<-full[idx$row[i],idx$col[i]]
  #fill imputed column
  idx$imputed[i]<-imp[[j]][,start2:end2][idx$row[i],idx$col[i]]
  #store imputed only for each percentage of missingness
  imputedonly[[j]]<-idx
}

new_list <- setNames(list(imp[[j]][,start2:end2]), placeHolder)
FULL <- append(FULL, new_list)  

 new_list2 <- setNames(list(imputedonly[[j]]), placeHolder2)
 PARTIAL <- append(PARTIAL, new_list2) 

}

missForest<- append(missForest, list(PARTIAL = PARTIAL,
                                     FULL = FULL
                                     ))

#NRMSE + fullMAE
nrmse <-list()
fullmae<-list()
NRMSE<-list()
fullMAE<-list()
for(j in 1:length(missForest[["FULL"]])){
  
placeHolder3 <- paste0( p[,j] * 100, " % missing")  

xi<- as.matrix(missForest[["FULL"]][[j]])
xt<-as.matrix(SCdf[,start:end])
xm<-as.matrix(t[[j]][,start:end]) 
  
nrmse[[j]]<-missForest::nrmse(ximp = xi, xmis = xm, xtrue = xt)

new_list <- setNames((nrmse[j]), placeHolder3)
NRMSE <- append(NRMSE, new_list) 

fullmae[j] <- mean(abs(xt - xi))

new_list2 <- setNames((fullmae[j]), placeHolder3)
fullMAE <- append(fullMAE, new_list2) 

}
 
#partialMAE
 partialmae <- list()  
 partialMAE<-list()
  for(j in 1:length(missForest[["PARTIAL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
    
  xt <- missForest[["PARTIAL"]][[j]][["original"]]
  xi <- missForest[["PARTIAL"]][[j]][["imputed"]]
  
  partialmae[j] <- mean(abs(xt - xi))
  
  new_list <- setNames((partialmae[j]), placeHolder3)
  partialMAE <- append(partialMAE, new_list) 
  }
 
#External check 1 missForest
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.1 <- list()
for(j in 1:length(missForest[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_Albumin ~ S_Total_protein, data = missForest[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original - imputed[[j]])/original)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.1 <- append(imputedBias.1, new_list) 
}

#External check 2 missForest
imputed<-list()
imputedSummary<-list()
imputedBias<-list()
imputedBias.2 <- list()
for(j in 1:length(missForest[["FULL"]])){
  placeHolder3 <- paste0( p[,j] * 100, " % missing")  
  imputedSummary[[j]] <- summary(lm(S_ALT ~ S_AST, data = missForest[["FULL"]][[j]]))
  imputed[[j]] <-imputedSummary[[j]][["coefficients"]][2,1]
  imputedBias[[j]]<- abs((original2 - imputed[[j]])/original2)
  new_list <- setNames((imputedBias[[j]]), placeHolder3)
  imputedBias.2 <- append(imputedBias.2, new_list) 
}
 
missForest<- append(missForest, list(NRMSE = NRMSE,
                                     partialMAE = partialMAE,
                                     fullMAE = fullMAE,
                                     imputedBias.1 = imputedBias.1,
                                     imputedBias.2 = imputedBias.2))  

results_list[[k]] <- MICErf

}

#nameing

 if((MCAR[1] %in% t[1])){
   missing<-"_MCAR"
 }

if((MAR[1] %in% t[1]) ){
  missing <-"_MAR"
}

if((MNAR[1] %in% t[1]) ){
  missing <-"_MNAR"
}

if(length(impcols) == 1){
   impco<- "_Company"
 }
 
  if(length(impcols) > 1){
  impco<- "_All"
  }
 
   if(length(impcols) < 1){
   impco<-"_noMeta"
 }

list_name <- paste("missForest_strata", missing, impco, sep = "")
assign(list_name, results_list, envir = .GlobalEnv)

n_entries <- length(results_list)
metrics <- c("NRMSE", "partialMAE", "fullMAE", "imputedBias.1", "imputedBias.2")

# Initialize a list to store the results
results <- list()

# Loop through the metrics
for (metric in metrics) {
  result_matrix <- matrix(NA, nrow = n_entries, ncol = length(results_list[[1]][[metric]]))
  
  # Loop through the list and extract the current metric values into the matrix
  for (i in 1:n_entries) {
    result_matrix[i, ] <- unlist(results_list[[i]][[metric]])
  }
  
  # Calculate mean and standard deviation for each column
  mean_values <- apply(result_matrix, 2, mean)
  std_dev_values <- apply(result_matrix, 2, sd)
  
  results[[metric]] <- list(mean = mean_values, std_dev = std_dev_values)
}

list_name <- paste("summary_missForest_strata", missing, impco, sep = "")
assign(list_name, results, envir = .GlobalEnv)


}

```

#save
```{r}

save(
       summary_MICErf_MAR_All,
summary_MICErf_MAR_All_Toxin,
       summary_MICErf_MAR_Company,
       summary_MICErf_MAR_noMeta,
               summary_MICErf_strata_MAR_All,
               summary_MICErf_strata_MAR_Company,
       summary_missForest_MAR_All,
     summary_missForest_MAR_Company,
       summary_missForest_MAR_noMeta,
               summary_missForest_strata_MAR_All,
               summary_missForest_strata_MAR_Company,
      MICErf_MAR_All,
MICErf_MAR_All_Toxin,
       MICErf_MAR_Company,
       MICErf_MAR_noMeta,
               MICErf_strata_MAR_All,
               MICErf_strata_MAR_Company,
       missForest_MAR_All,
       missForest_MAR_Company,
       missForest_MAR_noMeta,
               missForest_strata_MAR_All,
               missForest_strata_MAR_Company,
     file = "MARiteration500.Rdata")
save()

 #x <- SCdf[,tt]

#to not create missinginess in the following
miscols <- c(1:11)

#column to begin creating missingness
start <- which(colnames(SCdf) == "S_Creatinine")
#or start<-12
end<-ncol(SCdf)

forgg<-cbind(c[["data"]][["scores"]][,1:2], SCdf2)

ggplot(data = forgg, aes(x = PC1, y = PC2, color = Toxin)) + geom_point() + theme(legend.position = "none")



 discretePalette =c("#bef7ff", "#c0f1ff", "#c2ebff", "#c4e5ff", "#c6dfff", "#c8d9ff", "#cad3ff", "#cccdff", "#cec8ff", "#d0c2ff", "#d2bcff", "#d4b6ff", "#d6b0ff", "#d8aaff", "#daa4ff", "#dd9eff", "#df98ff", "#e192ff", "#e38cff", "#e586ff", "#e780ff", "#e97aff", "#eb75ff", "#ed6fff", "#ef69ff", "#f163ff", "#f35dff", "#f557ff", "#f751ff", "#f94bff", "#ffe434", "#fbdd34", "#f8d734", "#f4d035", "#f0c935", "#ecc235", "#e9bc35", "#e5b536", "#e1ae36", "#dda736", "#daa136", "#d69a37", "#d29337", "#cf8d37", "#cb8637", "#c77f38", "#c37838", "#c07238", "#bc6b38", "#b86439", "#b55e39", "#b15739", "#ad5039", "#a9493a", "#a6433a", "#a23c3a", "#9e353a", "#9a2e3b", "#97283b", "#93213b", "#20ff20", "#26c53d", "#2c8a5a", "#315076", "#371593", "red")
 
  theme = theme(legend.position = "none")
                                    

```
